create_design G.729A_Codec_raptor_project_default_1GE100-ES1
target_device 1GE100-ES1
add_design_file ./Src/G729A_asip_pkg.vhd
add_design_file ./Src/G729A_asip_basic_pkg.vhd
add_design_file ./Src/G729A_asip_arith_pkg.vhd
add_design_file ./Src/G729A_asip_adder_f.vhd
add_design_file ./Src/G729A_asip_addsub_pipeb.vhd
add_design_file ./Src/G729A_asip_op_pkg.vhd
add_design_file ./Src/G729A_asip_bjxlog.vhd
add_design_file ./Src/G729A_asip_cfg_pkg.vhd
add_design_file ./Src/G729A_asip_idec_2w_pkg.vhd
add_design_file ./Src/G729A_asip_cpu_2w_p6.vhd
add_design_file ./Src/G729A_asip_ftchlog_2w.vhd
add_design_file ./Src/G729A_asip_fwdlog_2w_p6.vhd
add_design_file ./Src/G729A_asip_idec.vhd
add_design_file ./Src/G729A_asip_idec_2w.vhd
add_design_file ./Src/G729A_asip_ifq.vhd
add_design_file ./Src/G729A_asip_lcstk.vhd
add_design_file ./Src/G729A_asip_lcstklog_2w.vhd
add_design_file ./Src/G729A_asip_lcstklog_ix.vhd
add_design_file ./Src/G729A_asip_logic.vhd
add_design_file ./Src/G729A_asip_lsu.vhd
add_design_file ./Src/G729A_asip_lu.vhd
add_design_file ./Src/G729A_asip_mulu_pipeb.vhd
add_design_file ./Src/G729A_asip_pipe_a_2w.vhd
add_design_file ./Src/G729A_asip_pipe_b.vhd
add_design_file ./Src/G729A_asip_pstllog_2w_p6.vhd
add_design_file ./Src/G729A_asip_pxlog.vhd
add_design_file ./Src/G729A_asip_rams.vhd
add_design_file ./Src/G729A_asip_regfile_16x16_2w.vhd
add_design_file ./Src/G729A_asip_romd_pkg.vhd
add_design_file ./Src/G729A_asip_romi_pkg.vhd
add_design_file ./Src/G729A_asip_roms.vhd
add_design_file ./Src/G729A_asip_roms_mif.vhd
add_design_file ./Src/G729A_asip_shftu.vhd
add_design_file ./Src/G729A_codec_intf_pkg.vhd
add_design_file ./Src/G729A_asip_spc.vhd
add_design_file ./Src/G729A_asip_top_2w.vhd
add_design_file ./Src/G729A_codec_sdp.vhd
add_design_file ./Src/G729A_codec_sdp_SYN.vhd
add_design_file ./Src/G729A_asip_adder.vhd
add_design_file ./Src/G729A_asip_idec_pkg.vhd
set_top_module G729A_CODEC_SDP_SYN
add_constraint_file G.729A_Codec_raptor_project_default_1GE100-ES1/constraints.sdc
analyze
