create_design DMA_AXI_raptor_project_default_1GE100-ES1
target_device 1GE100-ES1
add_design_file ./Src/dma_axi64_defines.v
add_design_file ./Src/dma_axi64.v
add_design_file ./Src/dma_axi64_apb_mux.v
add_design_file ./Src/dma_axi64_core0.v
add_design_file ./Src/dma_axi64_core0_arbiter.v
add_design_file ./Src/dma_axi64_core0_axim_cmd.v
add_design_file ./Src/dma_axi64_core0_axim_rd.v
add_design_file ./Src/dma_axi64_core0_axim_rdata.v
add_design_file ./Src/dma_axi64_core0_axim_resp.v
add_design_file ./Src/dma_axi64_core0_axim_timeout.v
add_design_file ./Src/dma_axi64_core0_axim_wdata.v
add_design_file ./Src/dma_axi64_core0_axim_wr.v
add_design_file ./Src/dma_axi64_core0_ch.v
add_design_file ./Src/dma_axi64_core0_ch_calc.v
add_design_file ./Src/dma_axi64_core0_ch_calc_addr.v
add_design_file ./Src/dma_axi64_core0_ch_calc_joint.v
add_design_file ./Src/dma_axi64_core0_ch_calc_size.v
add_design_file ./Src/dma_axi64_core0_ch_empty.v
add_design_file ./Src/dma_axi64_core0_ch_fifo.v
add_design_file ./Src/dma_axi64_core0_ch_fifo_ctrl.v
add_design_file ./Src/dma_axi64_core0_ch_fifo_ptr.v
add_design_file ./Src/dma_axi64_core0_ch_offsets.v
add_design_file ./Src/dma_axi64_core0_ch_outs.v
add_design_file ./Src/dma_axi64_core0_ch_periph_mux.v
add_design_file ./Src/dma_axi64_core0_ch_rd_slicer.v
add_design_file ./Src/dma_axi64_ch_reg_params.v
add_design_file ./Src/dma_axi64_core0_ch_reg.v
add_design_file ./Src/dma_axi64_core0_ch_reg_size.v
add_design_file ./Src/dma_axi64_core0_ch_remain.v
add_design_file ./Src/dma_axi64_core0_ch_wr_slicer.v
add_design_file ./Src/dma_axi64_core0_channels.v
add_design_file ./Src/dma_axi64_core0_channels_apb_mux.v
add_design_file ./Src/dma_axi64_core0_channels_mux.v
add_design_file ./Src/dma_axi64_core0_ctrl.v
add_design_file ./Src/dma_axi64_core0_top.v
add_design_file ./Src/dma_axi64_core0_wdt.v
add_design_file ./Src/dma_axi64_dual_core.v
add_design_file ./Src/dma_axi64_reg_params.v
add_design_file ./Src/dma_axi64_reg.v
add_design_file ./Src/dma_axi64_reg_core0.v
add_design_file ./Src/prgen_delay.v
add_design_file ./Src/prgen_demux8.v
add_design_file ./Src/prgen_fifo.v
add_design_file ./Src/prgen_joint_stall.v
add_design_file ./Src/prgen_min2.v
add_design_file ./Src/prgen_min3.v
add_design_file ./Src/prgen_mux8.v
add_design_file ./Src/prgen_or8.v
add_design_file ./Src/prgen_rawstat.v
add_design_file ./Src/prgen_scatter8_1.v
add_design_file ./Src/prgen_stall.v
add_design_file ./Src/prgen_swap_32.v
add_design_file ./Src/prgen_swap_64.v
add_design_file ./Src/dma_axi64_sr.v
set_top_module dma_axi64_sr
add_constraint_file DMA_AXI_raptor_project_default_1GE100-ES1/constraints.sdc
analyze
synthesize 
