create_clock -period 2.5 clk_0  
create_clock -period 1 clk_1 
create_clock -period 1.5 clk_2 
create_clock -period 1.8 clk_3  
create_clock -period 1.3 clk_4 
create_clock -period 2 clk_5 
create_clock -period 1.4 clk_6  
create_clock -period 2.4 clk_7 
create_clock -period 1 clk_8 
create_clock -period 1.9 clk_9  
create_clock -period 0.9 clk_10 
create_clock -period 2.6 clk_11 
create_clock -period 1.6 clk_12  
create_clock -period 2 clk_13 
create_clock -period 2.2 clk_14 
create_clock -period 1.2 clk_15 