create_design UnAmiga_Gameboy_raptor_project_default_1GE100-ES1
target_device 1GE100-ES1
add_design_file ./Src/Cores/GameBoy/rtl/build_id.sv
add_design_file ./Src/Cores/GameBoy/rtl/pll.v
add_design_file ./Src/Cores/GameBoy/rtl/dac.sv
add_design_file ./Src/Cores/GameBoy/rtl/gb.sv
add_design_file ./Src/Cores/GameBoy/rtl/iram.sv
add_design_file ./Src/Cores/GameBoy/rtl/keyboard.sv
add_design_file ./Src/Cores/GameBoy/rtl/lcd.sv
add_design_file ./Src/Cores/GameBoy/rtl/sdram.sv
add_design_file ./Src/Cores/GameBoy/rtl/sprite.sv
add_design_file ./Src/Cores/GameBoy/rtl/sprite_sort.sv
add_design_file ./Src/Cores/GameBoy/rtl/sprites.sv
add_design_file ./Src/Cores/GameBoy/rtl/timer.sv
add_design_file ./Src/Cores/GameBoy/rtl/video.sv
add_design_file ./Src/Cores/GameBoy/rtl/vram.sv
add_design_file ./Src/Cores/GameBoy/rtl/zpram.sv
add_design_file ./Src/Cores/GameBoy/rtl/BROM.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/CtrlModule/CharROM/CharROM_ROM.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/ZPUFlex/RTL/zpupkg.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/CtrlModule/Firmware/CtrlROM_ROM.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/CtrlModule/RTL/DualPortRAM_2RW_1Clock_Unreg.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/CtrlModule/RTL/OnScreenDisplay.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/CtrlModule/RTL/io_ps2_com.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/CtrlModule/RTL/spi.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/CtrlModule/RTL/interrupt_controller.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/CtrlModule/RTL/CtrlModule.vhd
add_design_file ./Src/Cores/GameBoy/rtl/t80/T80_Pack.vhd
add_design_file ./Src/Cores/GameBoy/rtl/t80/GBse.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/CtrlModule/RTL/OSD_Overlay.vhd
add_design_file ./Src/Cores/GameBoy/rtl/t80/T80.vhd
add_design_file ./Src/Cores/GameBoy/rtl/t80/T80_ALU.vhd
add_design_file ./Src/Cores/GameBoy/rtl/t80/T80_MCode.vhd
add_design_file ./Src/Cores/GameBoy/rtl/t80/T80_Reg.vhd
add_design_file ./Src/Cores/GameBoy/rtl/gbc_snd.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/menuOSD.vhd
add_design_file ./Src/Cores/GameBoy/menuOSD/ZPUFlex/RTL/zpu_core_flex.vhd
add_design_file ./Src/Cores/GameBoy/rtl/gb_mist.sv
set_top_module gb_mist
add_constraint_file UnAmiga_Gameboy_raptor_project_default_1GE100-ES1/constraints.sdc
analyze
