// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : ocla_wrapper2_v1_0.v
// Device     : gemini
// LiteX sha1 : --------
// Date       : 2024-03-22 15:21:07
//------------------------------------------------------------------------------
// This file is Copyright (c) 2022 RapidSilicon
//--------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module ocla_probe1024_mem_depth_32 #(
	parameter IP_TYPE 		= "OCLA",
	parameter IP_VERSION 	= 32'h1, 
	parameter IP_ID 		= 32'h5633547
)
(    input  wire          clk,
    input  wire          rstn,
    input  wire          jtag_tck,
    input  wire          jtag_tms,
    input  wire          jtag_tdi,
    output wire          jtag_tdo,
    input  wire          jtag_trst,
    input  wire  [1023:0] probe_1,
    input  wire          sampling_clk
);


//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

wire          sys_clk;
wire          rstn_rst;
wire          jtag_tck_1;
wire          jtag_tms_1;
wire          jtag_tdi_1;
wire          jtag_tdo_1;
wire          jtag_trst_1;
reg           probes_in = 1'd0;
reg   [151:0] axilite = 152'd0;
reg   [249:0] axifull = 250'd0;
reg           axi_sampling_clk = 1'd0;
wire          sampling_clk_1;
wire  [1023:0] probe_1_1;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign sys_clk = clk;
assign rstn_rst = rstn;
assign jtag_tck_1 = jtag_tck;
assign jtag_tms_1 = jtag_tms;
assign jtag_tdi_1 = jtag_tdi;
assign jtag_tdo = jtag_tdo_1;
assign jtag_trst_1 = jtag_trst;
assign probe_1_1 = probe_1;
assign sampling_clk_1 = sampling_clk;


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

ocla_debug_subsystem #(
	.AXI_Core_BaseAddress(32'h02000000),
	.Cores(1),
	.EIO_BaseAddress(32'h01000000),
	.EIO_Enable(0),
	.IF01_BaseAddress(32'h03000000),
	.IF01_Probes(64'h0000000000000001),
	.IF02_BaseAddress(32'h04000000),
	.IF02_Probes(64'h0000000000000000),
	.IF03_BaseAddress(32'h05000000),
	.IF03_Probes(64'h0000000000000000),
	.IF04_BaseAddress(32'h06000000),
	.IF04_Probes(64'h0000000000000000),
	.IF05_BaseAddress(32'h07000000),
	.IF05_Probes(64'h0000000000000000),
	.IF06_BaseAddress(32'h08000000),
	.IF06_Probes(64'h0000000000000000),
	.IF07_BaseAddress(32'h09000000),
	.IF07_Probes(64'h0000000000000000),
	.IF08_BaseAddress(32'h01000000),
	.IF08_Probes(64'h0000000000000000),
	.IF09_BaseAddress(32'h01100000),
	.IF09_Probes(64'h0000000000000000),
	.IF10_BaseAddress(32'h01200000),
	.IF10_Probes(64'h0000000000000000),
	.IF11_BaseAddress(32'h01300000),
	.IF11_Probes(64'h0000000000000000),
	.IF12_BaseAddress(32'h01400000),
	.IF12_Probes(64'h0000000000000000),
	.IF13_BaseAddress(32'h01500000),
	.IF13_Probes(64'h0000000000000000),
	.IF14_BaseAddress(32'h01600000),
	.IF14_Probes(64'h0000000000000000),
	.IF15_BaseAddress(32'h01700000),
	.IF15_Probes(64'h0000000000000000),
	.IP_ID(IP_ID),
	.IP_TYPE(IP_TYPE),
	.IP_VERSION(IP_VERSION),
	.Mem_Depth(32),
	.Mode("NATIVE"),
	.No_AXI_Bus(1),
	.No_Probes(1),
	.Probe01_Width(11'd1024),
	.Probe02_Width(11'd0),
	.Probe03_Width(11'd0),
	.Probe04_Width(11'd0),
	.Probe05_Width(11'd0),
	.Probe06_Width(11'd0),
	.Probe07_Width(11'd0),
	.Probe08_Width(11'd0),
	.Probe09_Width(11'd0),
	.Probe10_Width(11'd0),
	.Probe11_Width(11'd0),
	.Probe12_Width(11'd0),
	.Probe13_Width(11'd0),
	.Probe14_Width(11'd0),
	.Probe15_Width(11'd0),
	.Probes_Sum(14'd1024),
	.Sampling_Clk("SINGLE")
) ocla_debug_subsystem (
	.ACLK(sys_clk),
	.RESETn(rstn_rst),
	.axi4_probes(axifull),
	.axiLite_probes(axilite),
	.axi_sampling_clk(axi_sampling_clk),
	.jtag_tck(jtag_tck_1),
	.jtag_tdi(jtag_tdi_1),
	.jtag_tms(jtag_tms_1),
	.jtag_trst(jtag_trst_1),
	.native_sampling_clk(sampling_clk_1),
	.probes({probe_1_1}),
	.probes_in(probes_in),
	.jtag_tdo(jtag_tdo_1)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2024-03-22 15:21:07.
//------------------------------------------------------------------------------
