/* Generated by Yosys 0.38 (git sha1 6c475f1f1, gcc 11.2.1 -fPIC -Os) */

module and2(one, sec, s);
  input one;
  output s;
  input sec;
  wire _0_;
  wire _1_;
  wire _2_;
  wire one;
  wire s;
  wire sec;
  LUT2 #(
    .INIT_VALUE(4'b1000)
  ) _3_ (
    .A({ _1_, _0_ }),
    .Y(_2_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _4_ (
    .EN(1'b1),
    .I(one),
    .O(_0_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _5_ (
    .EN(1'b1),
    .I(sec),
    .O(_1_)
  );
  O_BUF _6_ (
    .I(_2_),
    .O(s)
  );
endmodule
