/* Generated by Yosys 0.38 (git sha1 6c475f1f1, gcc 11.2.1 -fPIC -Os) */

module and2(one, sec, s);
  input one;
  output s;
  input sec;
  wire \$auto_413 ;
  wire \$auto_414 ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:12.12-12.15" *)
  wire \$auto_416.one ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:14.13-14.14" *)
  wire \$auto_416.s ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:13.12-13.15" *)
  wire \$auto_416.sec ;
  wire \$flatten$auto_416.$auto_413 ;
  wire \$flatten$auto_416.$auto_414 ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:12.12-12.15" *)
  wire \$flatten$auto_416.$ibuf_one ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:13.12-13.15" *)
  wire \$flatten$auto_416.$ibuf_sec ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:14.13-14.14" *)
  wire \$flatten$auto_416.$obuf_s ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:12.12-12.15" *)
  wire \$ibuf_one ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:13.12-13.15" *)
  wire \$ibuf_sec ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:14.13-14.14" *)
  wire \$obuf_s ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:12.12-12.15" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:12.12-12.15" *)
  wire one;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:14.13-14.14" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:14.13-14.14" *)
  wire s;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:13.12-13.15" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24july/Validation/RTL_testcases/GUI_testcases/gui_run_incr_comp_project/incr_comp/run_1/incr_comp.srcs/sources_1/tmp.v:13.12-13.15" *)
  wire sec;
  fabric_and2 \$auto_415  (
    .\$auto_413 (\$auto_413 ),
    .\$auto_414 (\$auto_414 ),
    .\$ibuf_one (\$ibuf_one ),
    .\$ibuf_sec (\$ibuf_sec ),
    .\$obuf_s (\$obuf_s )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto_416.$ibuf$and2.$ibuf_one  (
    .EN(\$flatten$auto_416.$auto_413 ),
    .I(\$auto_416.one ),
    .O(\$flatten$auto_416.$ibuf_one )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto_416.$ibuf$and2.$ibuf_sec  (
    .EN(\$flatten$auto_416.$auto_414 ),
    .I(\$auto_416.sec ),
    .O(\$flatten$auto_416.$ibuf_sec )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto_416.$obuf$and2.$obuf_s  (
    .I(\$flatten$auto_416.$obuf_s ),
    .O(\$auto_416.s )
  );
  assign \$flatten$auto_416.$auto_414  = \$auto_414 ;
  assign \$flatten$auto_416.$auto_413  = \$auto_413 ;
  assign \$ibuf_one  = \$flatten$auto_416.$ibuf_one ;
  assign \$ibuf_sec  = \$flatten$auto_416.$ibuf_sec ;
  assign \$flatten$auto_416.$obuf_s  = \$obuf_s ;
  assign \$auto_416.one  = one;
  assign s = \$auto_416.s ;
  assign \$auto_416.sec  = sec;
endmodule
