//Verilog generated by VPR  from post-place-and-route implementation
module fabric_and2 (
    input \$ibuf_one ,
    input \$ibuf_sec ,
    output \$obuf_s ,
    output \$auto_413 ,
    output \$auto_414 
);

    //Wires
    wire \$ibuf_one_output_0_0 ;
    wire \$ibuf_sec_output_0_0 ;
    wire \lut_$auto_413_output_0_0 ;
    wire \lut_$auto_414_output_0_0 ;
    wire \lut_$obuf_s_output_0_0 ;
    wire \lut_$true_output_0_0 ;
    wire \lut_$obuf_s_input_0_2 ;
    wire \lut_$obuf_s_input_0_3 ;
    wire \$auto_413_input_0_0 ;
    wire \$auto_414_input_0_0 ;
    wire \$obuf_s_input_0_0 ;
    wire \lut_$auto_414_input_0_4 ;
    wire \lut_$auto_413_input_0_4 ;

    //IO assignments
    assign \$obuf_s  = \$obuf_s_input_0_0 ;
    assign \$auto_413  = \$auto_413_input_0_0 ;
    assign \$auto_414  = \$auto_414_input_0_0 ;
    assign \$ibuf_one_output_0_0  = \$ibuf_one ;
    assign \$ibuf_sec_output_0_0  = \$ibuf_sec ;

    //Interconnect
    fpga_interconnect \routing_segment_$ibuf_one_output_0_0_to_lut_$obuf_s_input_0_2  (
        .datain(\$ibuf_one_output_0_0 ),
        .dataout(\lut_$obuf_s_input_0_2 )
    );

    fpga_interconnect \routing_segment_$ibuf_sec_output_0_0_to_lut_$obuf_s_input_0_3  (
        .datain(\$ibuf_sec_output_0_0 ),
        .dataout(\lut_$obuf_s_input_0_3 )
    );

    fpga_interconnect \routing_segment_lut_$auto_413_output_0_0_to_$auto_413_input_0_0  (
        .datain(\lut_$auto_413_output_0_0 ),
        .dataout(\$auto_413_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto_414_output_0_0_to_$auto_414_input_0_0  (
        .datain(\lut_$auto_414_output_0_0 ),
        .dataout(\$auto_414_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$obuf_s_output_0_0_to_$obuf_s_input_0_0  (
        .datain(\lut_$obuf_s_output_0_0 ),
        .dataout(\$obuf_s_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto_414_input_0_4  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto_414_input_0_4 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto_413_input_0_4  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto_413_input_0_4 )
    );


    //Cell instances
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000010000000000000000)
    ) \lut_$auto_414  (
        .in({
            \lut_$auto_414_input_0_4 ,
            1'b0,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$auto_414_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000001)
    ) \lut_$true  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$true_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000010000000000000000)
    ) \lut_$auto_413  (
        .in({
            \lut_$auto_413_input_0_4 ,
            1'b0,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$auto_413_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000001000000000000)
    ) \lut_$obuf_s  (
        .in({
            1'b0,
            \lut_$obuf_s_input_0_3 ,
            \lut_$obuf_s_input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_$obuf_s_output_0_0 )
    );


endmodule
