// Verilated -*- SystemC -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_sc.h"
#include "Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__Syms.h"


VL_ATTR_COLD void Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_init_sub__TOP__0(Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushNamePrefix("co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2 ");
    tracep->declBus(c+14,"a", false,-1, 19,0);
    tracep->declBus(c+15,"b", false,-1, 17,0);
    tracep->declBus(c+16,"shift_right", false,-1, 5,0);
    tracep->declBit(c+144,"clk", false,-1);
    tracep->declBit(c+17,"reset", false,-1);
    tracep->declQuad(c+66,"z_out", false,-1, 37,0);
    tracep->declQuad(c+18,"expected_out", false,-1, 37,0);
    tracep->declBus(c+20,"mult1", false,-1, 31,0);
    tracep->declBus(c+21,"mult2", false,-1, 31,0);
    tracep->declQuad(c+22,"expected_out2", false,-1, 63,0);
    tracep->declQuad(c+24,"mult", false,-1, 63,0);
    tracep->declBus(c+26,"expected_out_shifted1", false,-1, 31,0);
    tracep->declBus(c+27,"expected_out_shifted2", false,-1, 31,0);
    tracep->declQuad(c+68,"z_out_netlist", false,-1, 37,0);
    tracep->declBus(c+28,"mismatch", false,-1, 31,0);
    tracep->pushNamePrefix("golden ");
    tracep->declBus(c+14,"a", false,-1, 19,0);
    tracep->declBus(c+15,"b", false,-1, 17,0);
    tracep->declBus(c+29,"shift_right", false,-1, 4,0);
    tracep->declBit(c+144,"clk", false,-1);
    tracep->declBit(c+17,"reset", false,-1);
    tracep->declQuad(c+66,"z_out", false,-1, 37,0);
    tracep->declBit(c+70,"DLY_B1", false,-1);
    tracep->declBit(c+71,"DLY_B2", false,-1);
    tracep->declBit(c+145,"ACC_FIR", false,-1);
    tracep->pushNamePrefix("DSP_inst ");
    tracep->declArray(c+146,"DSP_MODE", false,-1, 151,0);
    tracep->declBus(c+151,"COEFF1_0", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF1_1", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF1_2", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF1_3", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF2_0", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF2_1", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF2_2", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF2_3", false,-1, 9,0);
    tracep->declQuad(c+152,"OUTPUT_REG_EN", false,-1, 39,0);
    tracep->declQuad(c+152,"INPUT_REG_EN", false,-1, 39,0);
    tracep->declBus(c+30,"A1", false,-1, 9,0);
    tracep->declBus(c+31,"B1", false,-1, 8,0);
    tracep->declBus(c+72,"Z1", false,-1, 18,0);
    tracep->declBus(c+73,"DLY_B1", false,-1, 8,0);
    tracep->declBus(c+32,"A2", false,-1, 9,0);
    tracep->declBus(c+33,"B2", false,-1, 8,0);
    tracep->declBus(c+74,"Z2", false,-1, 18,0);
    tracep->declBus(c+75,"DLY_B2", false,-1, 8,0);
    tracep->declBit(c+144,"CLK", false,-1);
    tracep->declBit(c+17,"RESET", false,-1);
    tracep->declBus(c+1,"ACC_FIR", false,-1, 4,0);
    tracep->declBus(c+154,"FEEDBACK", false,-1, 2,0);
    tracep->declBit(c+155,"LOAD_ACC", false,-1);
    tracep->declBit(c+155,"UNSIGNED_A", false,-1);
    tracep->declBit(c+155,"UNSIGNED_B", false,-1);
    tracep->declBit(c+155,"SATURATE", false,-1);
    tracep->declBus(c+29,"SHIFT_RIGHT", false,-1, 4,0);
    tracep->declBit(c+155,"ROUND", false,-1);
    tracep->declBit(c+155,"SUBTRACT", false,-1);
    tracep->declBit(c+76,"subtract_reg", false,-1);
    tracep->declBus(c+77,"acc_fir_reg", false,-1, 4,0);
    tracep->declBus(c+78,"feedback_reg", false,-1, 2,0);
    tracep->declBus(c+79,"shift_right_reg1", false,-1, 4,0);
    tracep->declBus(c+80,"shift_right_reg2", false,-1, 4,0);
    tracep->declBit(c+81,"round_reg1", false,-1);
    tracep->declBit(c+82,"round_reg2", false,-1);
    tracep->declBit(c+83,"saturate_reg1", false,-1);
    tracep->declBit(c+84,"saturate_reg2", false,-1);
    tracep->declBit(c+85,"load_acc_reg", false,-1);
    tracep->declBus(c+86,"a1_reg", false,-1, 9,0);
    tracep->declBus(c+87,"a2_reg", false,-1, 9,0);
    tracep->declBus(c+88,"b1_reg", false,-1, 8,0);
    tracep->declBus(c+89,"b2_reg", false,-1, 8,0);
    tracep->declBit(c+90,"unsigned_a_reg", false,-1);
    tracep->declBit(c+91,"unsigned_b_reg", false,-1);
    tracep->declBit(c+3,"subtract_int", false,-1);
    tracep->declBus(c+2,"acc_fir_int", false,-1, 4,0);
    tracep->declBus(c+4,"feedback_int", false,-1, 2,0);
    tracep->declBus(c+92,"shift_right_int", false,-1, 4,0);
    tracep->declBit(c+93,"round_int", false,-1);
    tracep->declBit(c+94,"saturate_int", false,-1);
    tracep->declBit(c+5,"load_acc_int", false,-1);
    tracep->declBus(c+34,"a1_int", false,-1, 9,0);
    tracep->declBus(c+35,"a2_int", false,-1, 9,0);
    tracep->declBus(c+36,"b1_int", false,-1, 8,0);
    tracep->declBus(c+37,"b2_int", false,-1, 8,0);
    tracep->declBit(c+6,"unsigned_a_int", false,-1);
    tracep->declBit(c+7,"unsigned_b_int", false,-1);
    tracep->declQuad(c+95,"accumulator", false,-1, 63,0);
    tracep->declQuad(c+46,"add_sub_in", false,-1, 63,0);
    tracep->declQuad(c+48,"mult_out", false,-1, 63,0);
    tracep->declBus(c+50,"mult_out1", false,-1, 31,0);
    tracep->declBus(c+51,"mult_out2", false,-1, 31,0);
    tracep->declQuad(c+52,"add_sub_out", false,-1, 63,0);
    tracep->declQuad(c+97,"pre_shift", false,-1, 63,0);
    tracep->declBus(c+99,"shift_right_f0", false,-1, 31,0);
    tracep->declBus(c+100,"shift_right_f1", false,-1, 31,0);
    tracep->declBus(c+101,"round_f0", false,-1, 31,0);
    tracep->declBus(c+102,"round_f1", false,-1, 31,0);
    tracep->declBus(c+103,"saturate_f0", false,-1, 18,0);
    tracep->declBus(c+104,"saturate_f1", false,-1, 18,0);
    tracep->declQuad(c+66,"z_out", false,-1, 37,0);
    tracep->declQuad(c+105,"z_out_reg", false,-1, 37,0);
    tracep->declBus(c+73,"dly_b1", false,-1, 8,0);
    tracep->declBus(c+75,"dly_b2", false,-1, 8,0);
    tracep->declBus(c+54,"mult_a1", false,-1, 9,0);
    tracep->declBus(c+55,"mult_a2", false,-1, 9,0);
    tracep->declBus(c+38,"mult_b1", false,-1, 8,0);
    tracep->declBus(c+39,"mult_b2", false,-1, 8,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("netlist ");
    tracep->declBus(c+14,"a", false,-1, 19,0);
    tracep->declBus(c+15,"b", false,-1, 17,0);
    tracep->declBit(c+144,"clk", false,-1);
    tracep->declBit(c+17,"reset", false,-1);
    tracep->declBus(c+29,"shift_right", false,-1, 4,0);
    tracep->declQuad(c+68,"z_out", false,-1, 37,0);
    tracep->declBit(c+107,"DLY_B1", false,-1);
    tracep->declBit(c+108,"DLY_B2", false,-1);
    tracep->pushNamePrefix("DSP_inst ");
    tracep->declArray(c+146,"DSP_MODE", false,-1, 151,0);
    tracep->declBus(c+151,"COEFF1_0", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF1_1", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF1_2", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF1_3", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF2_0", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF2_1", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF2_2", false,-1, 9,0);
    tracep->declBus(c+151,"COEFF2_3", false,-1, 9,0);
    tracep->declQuad(c+152,"OUTPUT_REG_EN", false,-1, 39,0);
    tracep->declQuad(c+152,"INPUT_REG_EN", false,-1, 39,0);
    tracep->declBus(c+30,"A1", false,-1, 9,0);
    tracep->declBus(c+31,"B1", false,-1, 8,0);
    tracep->declBus(c+109,"Z1", false,-1, 18,0);
    tracep->declBus(c+110,"DLY_B1", false,-1, 8,0);
    tracep->declBus(c+32,"A2", false,-1, 9,0);
    tracep->declBus(c+33,"B2", false,-1, 8,0);
    tracep->declBus(c+111,"Z2", false,-1, 18,0);
    tracep->declBus(c+112,"DLY_B2", false,-1, 8,0);
    tracep->declBit(c+144,"CLK", false,-1);
    tracep->declBit(c+17,"RESET", false,-1);
    tracep->declBus(c+156,"ACC_FIR", false,-1, 4,0);
    tracep->declBus(c+154,"FEEDBACK", false,-1, 2,0);
    tracep->declBit(c+155,"LOAD_ACC", false,-1);
    tracep->declBit(c+155,"UNSIGNED_A", false,-1);
    tracep->declBit(c+155,"UNSIGNED_B", false,-1);
    tracep->declBit(c+155,"SATURATE", false,-1);
    tracep->declBus(c+29,"SHIFT_RIGHT", false,-1, 4,0);
    tracep->declBit(c+155,"ROUND", false,-1);
    tracep->declBit(c+155,"SUBTRACT", false,-1);
    tracep->declBit(c+113,"subtract_reg", false,-1);
    tracep->declBus(c+114,"acc_fir_reg", false,-1, 4,0);
    tracep->declBus(c+115,"feedback_reg", false,-1, 2,0);
    tracep->declBus(c+116,"shift_right_reg1", false,-1, 4,0);
    tracep->declBus(c+117,"shift_right_reg2", false,-1, 4,0);
    tracep->declBit(c+118,"round_reg1", false,-1);
    tracep->declBit(c+119,"round_reg2", false,-1);
    tracep->declBit(c+120,"saturate_reg1", false,-1);
    tracep->declBit(c+121,"saturate_reg2", false,-1);
    tracep->declBit(c+122,"load_acc_reg", false,-1);
    tracep->declBus(c+123,"a1_reg", false,-1, 9,0);
    tracep->declBus(c+124,"a2_reg", false,-1, 9,0);
    tracep->declBus(c+125,"b1_reg", false,-1, 8,0);
    tracep->declBus(c+126,"b2_reg", false,-1, 8,0);
    tracep->declBit(c+127,"unsigned_a_reg", false,-1);
    tracep->declBit(c+128,"unsigned_b_reg", false,-1);
    tracep->declBit(c+8,"subtract_int", false,-1);
    tracep->declBus(c+9,"acc_fir_int", false,-1, 4,0);
    tracep->declBus(c+10,"feedback_int", false,-1, 2,0);
    tracep->declBus(c+129,"shift_right_int", false,-1, 4,0);
    tracep->declBit(c+130,"round_int", false,-1);
    tracep->declBit(c+131,"saturate_int", false,-1);
    tracep->declBit(c+11,"load_acc_int", false,-1);
    tracep->declBus(c+40,"a1_int", false,-1, 9,0);
    tracep->declBus(c+41,"a2_int", false,-1, 9,0);
    tracep->declBus(c+42,"b1_int", false,-1, 8,0);
    tracep->declBus(c+43,"b2_int", false,-1, 8,0);
    tracep->declBit(c+12,"unsigned_a_int", false,-1);
    tracep->declBit(c+13,"unsigned_b_int", false,-1);
    tracep->declQuad(c+132,"accumulator", false,-1, 63,0);
    tracep->declQuad(c+56,"add_sub_in", false,-1, 63,0);
    tracep->declQuad(c+58,"mult_out", false,-1, 63,0);
    tracep->declBus(c+60,"mult_out1", false,-1, 31,0);
    tracep->declBus(c+61,"mult_out2", false,-1, 31,0);
    tracep->declQuad(c+62,"add_sub_out", false,-1, 63,0);
    tracep->declQuad(c+134,"pre_shift", false,-1, 63,0);
    tracep->declBus(c+136,"shift_right_f0", false,-1, 31,0);
    tracep->declBus(c+137,"shift_right_f1", false,-1, 31,0);
    tracep->declBus(c+138,"round_f0", false,-1, 31,0);
    tracep->declBus(c+139,"round_f1", false,-1, 31,0);
    tracep->declBus(c+140,"saturate_f0", false,-1, 18,0);
    tracep->declBus(c+141,"saturate_f1", false,-1, 18,0);
    tracep->declQuad(c+68,"z_out", false,-1, 37,0);
    tracep->declQuad(c+142,"z_out_reg", false,-1, 37,0);
    tracep->declBus(c+110,"dly_b1", false,-1, 8,0);
    tracep->declBus(c+112,"dly_b2", false,-1, 8,0);
    tracep->declBus(c+64,"mult_a1", false,-1, 9,0);
    tracep->declBus(c+65,"mult_a2", false,-1, 9,0);
    tracep->declBus(c+44,"mult_b1", false,-1, 8,0);
    tracep->declBus(c+45,"mult_b2", false,-1, 8,0);
    tracep->popNamePrefix(3);
}

VL_ATTR_COLD void Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_init_top(Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_init_top\n"); );
    // Body
    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_register(Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_full_sub_0(Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_full_top_0\n"); );
    // Init
    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root*>(voidSelf);
    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_full_sub_0(Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vco_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    VlWide<5>/*159:0*/ __Vtemp_hd7818bb3__0;
    // Body
    bufp->fullCData(oldp+1,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT____Vcellinp__DSP_inst__ACC_FIR),5);
    bufp->fullCData(oldp+2,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__acc_fir_int),5);
    bufp->fullBit(oldp+3,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__subtract_int));
    bufp->fullCData(oldp+4,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__feedback_int),3);
    bufp->fullBit(oldp+5,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__load_acc_int));
    bufp->fullBit(oldp+6,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__unsigned_a_int));
    bufp->fullBit(oldp+7,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__unsigned_b_int));
    bufp->fullBit(oldp+8,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__subtract_int));
    bufp->fullCData(oldp+9,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__acc_fir_int),5);
    bufp->fullCData(oldp+10,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__feedback_int),3);
    bufp->fullBit(oldp+11,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__load_acc_int));
    bufp->fullBit(oldp+12,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__unsigned_a_int));
    bufp->fullBit(oldp+13,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__unsigned_b_int));
    bufp->fullIData(oldp+14,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__a),20);
    bufp->fullIData(oldp+15,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__b),18);
    bufp->fullCData(oldp+16,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__shift_right),6);
    bufp->fullBit(oldp+17,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__reset));
    bufp->fullQData(oldp+18,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__expected_out),38);
    bufp->fullIData(oldp+20,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__mult1),32);
    bufp->fullIData(oldp+21,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__mult2),32);
    bufp->fullQData(oldp+22,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__expected_out2),64);
    bufp->fullQData(oldp+24,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__mult),64);
    bufp->fullIData(oldp+26,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__expected_out_shifted1),32);
    bufp->fullIData(oldp+27,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__expected_out_shifted2),32);
    bufp->fullIData(oldp+28,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__mismatch),32);
    bufp->fullCData(oldp+29,((0x1fU & (IData)(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__shift_right))),5);
    bufp->fullSData(oldp+30,((0x3ffU & vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__a)),10);
    bufp->fullSData(oldp+31,((0x1ffU & vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__b)),9);
    bufp->fullSData(oldp+32,((0x3ffU & (vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__a 
                                        >> 0xaU))),10);
    bufp->fullSData(oldp+33,((0x1ffU & (vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__b 
                                        >> 9U))),9);
    bufp->fullSData(oldp+34,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__a1_int),10);
    bufp->fullSData(oldp+35,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__a2_int),10);
    bufp->fullSData(oldp+36,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__b1_int),9);
    bufp->fullSData(oldp+37,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__b2_int),9);
    bufp->fullSData(oldp+38,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__mult_b1),9);
    bufp->fullSData(oldp+39,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__mult_b2),9);
    bufp->fullSData(oldp+40,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__a1_int),10);
    bufp->fullSData(oldp+41,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__a2_int),10);
    bufp->fullSData(oldp+42,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__b1_int),9);
    bufp->fullSData(oldp+43,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__b2_int),9);
    bufp->fullSData(oldp+44,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__mult_b1),9);
    bufp->fullSData(oldp+45,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__mult_b2),9);
    bufp->fullQData(oldp+46,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__add_sub_in),64);
    bufp->fullQData(oldp+48,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__mult_out),64);
    bufp->fullIData(oldp+50,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__mult_out1),32);
    bufp->fullIData(oldp+51,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__mult_out2),32);
    bufp->fullQData(oldp+52,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__add_sub_out),64);
    bufp->fullSData(oldp+54,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__mult_a1),10);
    bufp->fullSData(oldp+55,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__mult_a2),10);
    bufp->fullQData(oldp+56,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__add_sub_in),64);
    bufp->fullQData(oldp+58,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__mult_out),64);
    bufp->fullIData(oldp+60,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__mult_out1),32);
    bufp->fullIData(oldp+61,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__mult_out2),32);
    bufp->fullQData(oldp+62,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__add_sub_out),64);
    bufp->fullSData(oldp+64,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__mult_a1),10);
    bufp->fullSData(oldp+65,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__mult_a2),10);
    bufp->fullQData(oldp+66,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__z_out),38);
    bufp->fullQData(oldp+68,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__z_out),38);
    bufp->fullBit(oldp+70,((1U & (IData)(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__dly_b1))));
    bufp->fullBit(oldp+71,((1U & (IData)(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__dly_b2))));
    bufp->fullIData(oldp+72,((0x7ffffU & (IData)(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__z_out))),19);
    bufp->fullSData(oldp+73,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__dly_b1),9);
    bufp->fullIData(oldp+74,((0x7ffffU & (IData)((vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__z_out 
                                                  >> 0x13U)))),19);
    bufp->fullSData(oldp+75,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__dly_b2),9);
    bufp->fullBit(oldp+76,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__subtract_reg));
    bufp->fullCData(oldp+77,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__acc_fir_reg),5);
    bufp->fullCData(oldp+78,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__feedback_reg),3);
    bufp->fullCData(oldp+79,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__shift_right_reg1),5);
    bufp->fullCData(oldp+80,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__shift_right_reg2),5);
    bufp->fullBit(oldp+81,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__round_reg1));
    bufp->fullBit(oldp+82,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__round_reg2));
    bufp->fullBit(oldp+83,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__saturate_reg1));
    bufp->fullBit(oldp+84,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__saturate_reg2));
    bufp->fullBit(oldp+85,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__load_acc_reg));
    bufp->fullSData(oldp+86,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__a1_reg),10);
    bufp->fullSData(oldp+87,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__a2_reg),10);
    bufp->fullSData(oldp+88,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__b1_reg),9);
    bufp->fullSData(oldp+89,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__b2_reg),9);
    bufp->fullBit(oldp+90,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__unsigned_a_reg));
    bufp->fullBit(oldp+91,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__unsigned_b_reg));
    bufp->fullCData(oldp+92,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__shift_right_int),5);
    bufp->fullBit(oldp+93,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__round_int));
    bufp->fullBit(oldp+94,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__saturate_int));
    bufp->fullQData(oldp+95,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__accumulator),64);
    bufp->fullQData(oldp+97,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__pre_shift),64);
    bufp->fullIData(oldp+99,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__shift_right_f0),32);
    bufp->fullIData(oldp+100,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__shift_right_f1),32);
    bufp->fullIData(oldp+101,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__round_f0),32);
    bufp->fullIData(oldp+102,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__round_f1),32);
    bufp->fullIData(oldp+103,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__saturate_f0),19);
    bufp->fullIData(oldp+104,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__saturate_f1),19);
    bufp->fullQData(oldp+105,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__DSP_inst__DOT__z_out_reg),38);
    bufp->fullBit(oldp+107,((1U & (IData)(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__dly_b1))));
    bufp->fullBit(oldp+108,((1U & (IData)(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__dly_b2))));
    bufp->fullIData(oldp+109,((0x7ffffU & (IData)(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__z_out))),19);
    bufp->fullSData(oldp+110,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__dly_b1),9);
    bufp->fullIData(oldp+111,((0x7ffffU & (IData)((vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__z_out 
                                                   >> 0x13U)))),19);
    bufp->fullSData(oldp+112,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__dly_b2),9);
    bufp->fullBit(oldp+113,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__subtract_reg));
    bufp->fullCData(oldp+114,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__acc_fir_reg),5);
    bufp->fullCData(oldp+115,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__feedback_reg),3);
    bufp->fullCData(oldp+116,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__shift_right_reg1),5);
    bufp->fullCData(oldp+117,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__shift_right_reg2),5);
    bufp->fullBit(oldp+118,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__round_reg1));
    bufp->fullBit(oldp+119,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__round_reg2));
    bufp->fullBit(oldp+120,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__saturate_reg1));
    bufp->fullBit(oldp+121,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__saturate_reg2));
    bufp->fullBit(oldp+122,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__load_acc_reg));
    bufp->fullSData(oldp+123,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__a1_reg),10);
    bufp->fullSData(oldp+124,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__a2_reg),10);
    bufp->fullSData(oldp+125,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__b1_reg),9);
    bufp->fullSData(oldp+126,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__b2_reg),9);
    bufp->fullBit(oldp+127,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__unsigned_a_reg));
    bufp->fullBit(oldp+128,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__unsigned_b_reg));
    bufp->fullCData(oldp+129,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__shift_right_int),5);
    bufp->fullBit(oldp+130,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__round_int));
    bufp->fullBit(oldp+131,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__saturate_int));
    bufp->fullQData(oldp+132,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__accumulator),64);
    bufp->fullQData(oldp+134,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__pre_shift),64);
    bufp->fullIData(oldp+136,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__shift_right_f0),32);
    bufp->fullIData(oldp+137,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__shift_right_f1),32);
    bufp->fullIData(oldp+138,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__round_f0),32);
    bufp->fullIData(oldp+139,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__round_f1),32);
    bufp->fullIData(oldp+140,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__saturate_f0),19);
    bufp->fullIData(oldp+141,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__saturate_f1),19);
    bufp->fullQData(oldp+142,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__netlist__DOT__DSP_inst__DOT__z_out_reg),38);
    bufp->fullBit(oldp+144,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__clk));
    bufp->fullBit(oldp+145,(vlSelf->co_sim_unsigned_accum_output_shifted_rounded_saturated_overflow_inst_dsp19x2__DOT__golden__DOT__ACC_FIR));
    __Vtemp_hd7818bb3__0[0U] = 0x4c415445U;
    __Vtemp_hd7818bb3__0[1U] = 0x43554d55U;
    __Vtemp_hd7818bb3__0[2U] = 0x595f4143U;
    __Vtemp_hd7818bb3__0[3U] = 0x5449504cU;
    __Vtemp_hd7818bb3__0[4U] = 0x4d554cU;
    bufp->fullWData(oldp+146,(__Vtemp_hd7818bb3__0),152);
    bufp->fullSData(oldp+151,(0U),10);
    bufp->fullQData(oldp+152,(0x46414c5345ULL),40);
    bufp->fullCData(oldp+154,(0U),3);
    bufp->fullBit(oldp+155,(1U));
    bufp->fullCData(oldp+156,(0U),5);
}
